call _SetupIDEProject(expand("<sfile>"))
" if g:project is customized, it may be necessary to call:
" call _PerformProjectSettings()

exec printf("cd %s", project.loc.Droot)
let g:grepper.tools = ['git', 'grep']

" === Scala project stuff

" ... activate the scala support plugin
" packadd simlei_metalsnvim_scalaide

